# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_teams_num_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='num_losses',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
