# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('networth', models.IntegerField(blank=True, null=True)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlaysIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('points_scored', models.IntegerField(blank=True, null=True)),
                ('away_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team_id_playsin', to='backend.Team')),
                ('home_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team_id_playsin', to='backend.Team')),
                ('player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Player')),
            ],
            options={
                'db_table': 'PlaysIn',
            },
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together=set([('player_id', 'date', 'home_team_id', 'away_team_id')]),
        ),
    ]
