# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20170423_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_year',
            new_name='height',
        ),
    ]
