# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20170426_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='played_id',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
