# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20170426_1837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together=set([]),
        ),
    ]
