# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20170426_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team_game', to='backend.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team_game', to='backend.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='backend.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='backend.Team'),
        ),
        migrations.AddField(
            model_name='playsin',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team_playsin', to='backend.Team'),
        ),
        migrations.AddField(
            model_name='playsin',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team_playsin', to='backend.Team'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_id',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('date', 'home_team', 'away_team')]),
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='home_team_id',
        ),
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together=set([('date', 'home_team', 'away_team')]),
        ),
        migrations.RemoveField(
            model_name='playsin',
            name='away_team_id',
        ),
        migrations.RemoveField(
            model_name='playsin',
            name='home_team_id',
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together=set([('player_id', 'date', 'home_team', 'away_team')]),
        ),
    ]
