# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20170429_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='age',
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
