# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GameScore',
            },
        ),
        migrations.RenameField(
            model_name='player',
            old_name='age',
            new_name='first_year',
        ),
        migrations.AddField(
            model_name='player',
            name='player_name',
            field=models.CharField(default=1999, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='Cleveland', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='played_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='away_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team_id', to='dashboard.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='home_team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team_id', to='dashboard.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together=set([('date', 'home_team_id', 'away_team_id')]),
        ),
    ]
