# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170423_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('winning_team', models.CharField(blank=True, choices=[('HOME', 'Home Team'), ('AWAY', 'Away Team')], default=None, max_length=20, null=True)),
                ('away_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team_id_game', to='dashboard.Team')),
                ('home_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team_id_game', to='dashboard.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('date', 'home_team_id', 'away_team_id')]),
        ),
    ]
