# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170423_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('coach_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Team')),
            ],
            options={
                'db_table': 'Coaches',
            },
        ),
    ]
