# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20170423_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='coach',
            table='Coach',
        ),
        migrations.AlterModelTable(
            name='game',
            table='Game',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Owner',
        ),
        migrations.AlterModelTable(
            name='player',
            table='Player',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
