# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20170426_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_city',
            field=models.CharField(max_length=19),
        ),
    ]
