# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20170426_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playsin',
            old_name='away_team',
            new_name='away_team_id',
        ),
        migrations.RenameField(
            model_name='playsin',
            old_name='home_team',
            new_name='home_team_id',
        ),
        migrations.AlterUniqueTogether(
            name='playsin',
            unique_together=set([('player_id', 'date', 'home_team_id', 'away_team_id')]),
        ),
    ]
