# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20170426_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_team',
            new_name='away_team_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_team',
            new_name='home_team_id',
        ),
        migrations.RenameField(
            model_name='gamescore',
            old_name='away_team',
            new_name='away_team_id',
        ),
        migrations.RenameField(
            model_name='gamescore',
            old_name='home_team',
            new_name='home_team_id',
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set([('date', 'home_team_id', 'away_team_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='gamescore',
            unique_together=set([('date', 'home_team_id', 'away_team_id')]),
        ),
    ]
